Repository KW-GIRIGIRI/kw-rental, pull requests merged in 2023-04, with the labels that each got.

#25 Feat : 품목 예약 이력 컴포넌트 구현
  src/assets/icon-excel.svg
  src/components/ItemReserveHist/ItemResHistTbl/index.jsx
  src/components/ItemReserveHist/ItemResHistTbl/style.js
  src/components/ItemReserveHist/index.jsx
  src/components/ItemReserveHist/style.js
  src/pages/EquipmentItemDetail/index.jsx
Labels: 📁 Feat

#26 기자재 조회, 추가, 수정, 삭제 api 연결
  src/api/api.js
  src/components/DetailDesc/DetailDescInput/index.jsx
  src/components/DetailDesc/index.jsx
  src/components/EquipListWrap/GalType/index.jsx
  src/components/Modal/DeleteCheck/index.jsx
  src/hook/useInput.js
  src/modules/Image/style.js
  src/modules/Input/index.jsx
  src/modules/Textarea/index.jsx
  src/pages/AddEquipment/index.jsx
  src/pages/EquipmentDetail/index.jsx
  src/pages/EquipmentItemDetail/index.jsx
  src/pages/EquipmentList/index.jsx
Labels: 📁 Feat

#27 모달 구현
  src/components/Modal/DeleteCheck/index.jsx
  src/components/Modal/SearchError/index.jsx
  src/components/Modal/index.jsx
  src/components/Modal/style.js
  src/hook/useModal.js
  src/modules/Button/index.jsx
  src/modules/Button/style.js
  src/pages/AddEquipment/index.jsx
  src/pages/EquipmentDetail/index.jsx
  src/pages/EquipmentList/index.jsx
Labels: 📁 Feat

#29 관리자 페이지 api 연결 및 기능 수정
  src/api/api.js
  src/components/DetailDesc/DetailDescInput/index.jsx
  src/components/DetailDesc/index.jsx
  src/components/DetailDesc/style.js
  src/components/EquipListWrap/GalType/index.jsx
  src/components/EquipListWrap/ListType/index.jsx
  src/data/category.js
  src/hook/useToggle.js
  src/modules/Button/index.jsx
  src/modules/Input/index.jsx
  src/modules/Textarea/index.jsx
  src/modules/Toggle/index.jsx
  src/modules/Toggle/style.js
  src/pages/AddEquipment/index.jsx
  src/pages/AddEquipment/style.js
  src/pages/EquipmentDetail/index.jsx
  src/pages/EquipmentDetail/style.js
  src/pages/EquipmentList/index.jsx
Labels: 📁 Feat, 🔧 Fix, 🧩 Refactor

#30 Fix : 기자재일 경우, 수정 페이지에서 품목 리스트 출력 오류 수정
  src/pages/AddEquipment/index.jsx
Labels: 🔧 Fix

#38 api 연결 및 오류 수정
  src/api/api.js
  src/assets/icon-check-gray.svg
  src/assets/icon-check-navy.svg
  src/assets/icon-check-white.svg
  src/components/AddCartEquip/index.jsx
  src/components/AddCartEquip/style.js
  src/components/Application/ApplicationForm/index.jsx
  src/components/Application/ApplicationForm/style.js
  src/components/Application/ToS/index.jsx
  src/components/Application/ToS/style.js
  src/components/Application/index.jsx
  src/components/Application/style.js
  src/components/EquipCartList/ListItem/index.jsx
  src/components/EquipCartList/ListItem/style.js
  src/components/EquipCartList/ModifyModal/index.jsx
  src/components/EquipCartList/index.jsx
  src/components/EquipCartList/style.js
  src/components/Modal/style.js
  src/hook/useModal.js
  src/modules/Button/style.js
  src/modules/Input/style.js
  src/pages/EquipmentBox/index.jsx
  src/pages/EquipmentCart/EquipmentBox/index.jsx
  src/pages/EquipmentCart/EquipmentBox/style.js
  src/pages/EquipmentCart/RentalApplication/index.jsx
  src/pages/EquipmentCart/RentalApplication/style.js
  src/pages/EquipmentCart/RentalSuccess/index.jsx
  src/pages/EquipmentCart/RentalSuccess/style.js
  src/pages/EquipmentCart/index.jsx
  src/pages/EquipmentCart/style.js
  src/pages/EquipmentDetail/index.jsx
  src/pages/EquipmentList/index.jsx
  src/pages/RentalSuccess/index.jsx
  src/router/Router.js
Labels: 🚨 Bug, 📁 Feat, 🔧 Fix

#47 품목 기능 연결
  src/api/api.js
  src/components/DetailDesc/DetailDescInput/index.jsx
  src/components/DetailDesc/style.js
  src/components/ItemListWrap/ItemList/index.jsx
  src/components/ItemListWrap/ItemListComp/index.jsx
  src/components/ItemListWrap/ItemListComp/style.js
  src/components/ItemListWrap/index.jsx
  src/components/ItemListWrap/style.js
  src/pages/AddEquipment/index.jsx
  src/pages/EquipmentDetail/index.jsx
  src/pages/EquipmentItemDetail/index.jsx
Labels: 📁 Feat

#48 Modify page
  src/api/api.js
  src/components/AddCartEquip/index.jsx
  src/components/Application/ApplicationForm/index.jsx
  src/components/Application/ApplicationForm/style.js
  src/components/Application/ToS/index.jsx
  src/components/Application/index.jsx
  src/components/DetailDesc/DetailDescInput/index.jsx
  src/components/EquipCartList/ListItem/index.jsx
  src/components/EquipCartList/ModifyModal/index.jsx
  src/components/EquipListWrap/GalType/index.jsx
  src/components/EquipListWrap/GalType/style.js
  src/components/EquipListWrap/ListType/index.jsx
  src/components/ItemListWrap/index.jsx
  src/components/NavBar/index.jsx
  src/context/Context.js
  src/modules/Input/style.js
  src/pages/AddEquipment/index.jsx
  src/pages/EquipmentCart/EquipmentBox/index.jsx
  src/pages/EquipmentCart/RentalApplication/index.jsx
  src/pages/EquipmentCart/RentalSuccess/index.jsx
  src/pages/EquipmentDetail/index.jsx
  src/pages/EquipmentItemDetail/index.jsx
  src/pages/EquipmentList/index.jsx
  src/pages/EquipmentRental/index.jsx
  src/pages/History/index.jsx
  src/pages/History/style.js
  src/pages/Notice/index.jsx
  src/pages/RentalStatus/index.jsx
  src/router/Router.js
  src/styles/theme.js
Labels: 📁 Feat, 🔧 Fix

#52 대여 페이지 컴포넌트
  src/assets/icon-exclamation.svg
  src/assets/icon-sendEmail.svg
  src/components/EquipCartList/ModifyModal/index.jsx
  src/components/EquipSched/CancelModal/index.jsx
  src/components/EquipSched/CancelModal/style.js
  src/components/EquipSched/ReturnModal/index.jsx
  src/components/EquipSched/ReturnModal/style.js
  src/components/EquipSched/index.jsx
  src/components/EquipSched/style.js
  src/components/Modal/style.js
  src/components/NavBar/index.jsx
  src/components/SchedList/SchedListComp/index.jsx
  src/components/SchedList/SchedListComp/style.js
  src/components/SchedList/index.jsx
  src/components/SchedList/style.js
  src/context/Context.js
  src/pages/EquipmentList/index.jsx
Labels: 📁 Feat, 🧩 Refactor

#54 로그인, 회원가입, 비밀번호 찾기 페이지
  package-lock.json
  package.json
  src/assets/icon-blockPassword.svg
  src/assets/icon-showPassword.svg
  src/components/Header/index.jsx
  src/layouts/AuthWrapper/index.jsx
  src/layouts/AuthWrapper/style.js
  src/modules/Button/style.js
  src/modules/Input/style.js
  src/pages/AuthSuccess/index.jsx
  src/pages/AuthSuccess/style.js
  src/pages/EquipmentList/index.jsx
  src/pages/ForgotPassword/index.jsx
  src/pages/ForgotPassword/style.js
  src/pages/Login/index.jsx
  src/pages/Login/style.js
  src/pages/SignUp/index.jsx
  src/pages/SignUp/style.js
  src/router/Router.js
Labels: 🪡 Design, 📁 Feat
