Repository KW-GIRIGIRI/kw-rental, pull requests merged in 2023-05, with the labels that each got.

#58 Refactor: 내 대여 정보 페이지 수정
  src/components/UserHist/index.jsx
  src/components/UserHist/style.js
  src/components/UserState/index.jsx
  src/components/UserState/style.js
  src/pages/EquipRentalHistory/style.js
  src/pages/History/EquipRentalHistory/index.jsx
  src/pages/History/LabRentalHistory/index.jsx
  src/pages/History/PenaltyHistory/index.jsx
  src/pages/History/style.js
  src/pages/LabRentalHistory/style.js
  src/pages/PenaltyHistory/style.js
  src/router/Router.js
Labels: 🧩 Refactor

#59 계정 설정 페이지
  src/assets/icon-menu.svg
  src/assets/icon-sendEmail.svg
  src/components/AccountSettingComp/ChangeAccount/index.jsx
  src/components/AccountSettingComp/ChangeAccount/style.js
  src/components/AccountSettingComp/CheckPw/index.jsx
  src/components/AccountSettingComp/CheckPw/style.js
  src/components/AccountSettingComp/index.jsx
  src/components/AccountSettingComp/style.js
  src/components/EquipSched/CancelModal/index.jsx
  src/components/EquipSched/CancelModal/style.js
  src/components/Header/HeaderUserInfo/index.jsx
  src/components/Header/index.jsx
  src/components/Header/style.js
  src/components/NavBar/index.jsx
  src/components/ProfileMenu/index.jsx
  src/components/ProfileMenu/style.js
  src/pages/SetAccount/index.jsx
  src/pages/SetAccount/style.js
  src/pages/SignUp/index.jsx
  src/router/Router.js
Labels: 🪡 Design, 📁 Feat

#61 Feat: 관리자 히스토리 페이지 구현
  package.json
  src/components/EquipStatistics/index.jsx
  src/components/EquipStatistics/style.js
  src/components/PenaltyState/index.jsx
  src/components/PenaltyState/style.js
  src/pages/History/EquipRentalHistory/index.jsx
  src/pages/History/PenaltyHistory/index.jsx
  src/pages/History/index.jsx
  src/pages/History/style.js
  src/router/Router.js
Labels: 📁 Feat

#62 api 연결 및 오류 수정
  package-lock.json
  src/api/api.js
  src/assets/icon-exclamation-gray.svg
  src/components/DatePicker/index.jsx
  src/components/EquipCartList/ModifyModal/index.jsx
  src/components/EquipSched/CancelModal/index.jsx
  src/components/EquipSched/ReturnModal/index.jsx
  src/components/EquipSched/ReturnModal/style.js
  src/components/EquipSched/index.jsx
  src/components/EquipSched/style.js
  src/components/ItemCalendar/index.jsx
  src/components/ItemCalendar/style.js
  src/components/SchedList/SchedListComp/index.jsx
  src/components/SchedList/SchedListComp/style.js
  src/components/SchedList/index.jsx
  src/components/SchedList/style.js
  src/components/WeekPicker/index.jsx
  src/modules/Button/index.jsx
  src/pages/EquipmentCart/RentalSuccess/index.jsx
  src/pages/EquipmentDetail/index.jsx
  src/pages/Login/index.jsx
  src/pages/RentalStatus/index.jsx
  src/pages/RentalStatus/style.js
Labels: 📁 Feat, 🔧 Fix

#64 Feat: 사용자 랩실 마크업
  package.json
  src/components/Application/ApplicationForm/index.jsx
  src/components/Application/ApplicationForm/style.js
  src/components/Application/LabConfirmTable/index.jsx
  src/components/Application/LabConfirmTable/style.js
  src/components/Application/index.jsx
  src/components/Application/style.js
  src/components/NavBar/index.jsx
  src/components/ToastUI/ToastEditor/index.jsx
  src/components/ToastUI/ToastViewer/index.jsx
  src/components/ToastUI/index.jsx
  src/components/UserState/style.js
  src/context/Context.js
  src/pages/LabRental/LabInformation/index.jsx
  src/pages/LabRental/LabRentalApplication/index.jsx
  src/pages/LabRental/LabRentalApplication/style.js
  src/pages/LabRental/LabRentalSched/index.jsx
  src/pages/LabRental/LabRentalSched/style.js
  src/pages/LabRental/LabRentalSuccess/index.jsx
  src/pages/LabRental/LabRentalSuccess/style.js
  src/pages/LabRental/index.jsx
  src/pages/LabRental/style.js
  src/router/Router.js
Labels: 🪡 Design, 📁 Feat

#65 Feat: 현재 내 대여 상태 api 구현
  src/api/api.js
  src/components/UserState/index.jsx
Labels: 📁 Feat

#66 수령 확인 및 반납 확인 기능 연결
  package-lock.json
  package.json
  src/api/api.js
  src/components/DatePicker/index.jsx
  src/components/DetailDesc/DetailDescInput/index.jsx
  src/components/EquipSched/ReturnModal/index.jsx
  src/components/EquipSched/ReturnModal/style.js
  src/components/EquipSched/index.jsx
  src/components/ItemCalendar/style.js
  src/components/SchedList/SchedListComp/index.jsx
  src/components/SchedList/index.jsx
  src/components/SchedList/style.js
  src/index.js
  src/pages/AddEquipment/index.jsx
  src/store/index.js
  src/store/reducer/authReceiveSlice.js
Labels: 📁 Feat

#69 랩실 페이지 마크업
  package-lock.json
  src/components/Application/ApplicationForm/index.jsx
  src/components/Application/ApplicationForm/style.js
  src/components/EquipListWrap/GalType/style.js
  src/components/LabCalendar/index.jsx
  src/components/LabCalendar/style.js
  src/components/LabReserveWrap/index.jsx
  src/components/LabReserveWrap/style.js
  src/components/ToastUI/ToastEditor/index.jsx
  src/context/Context.js
  src/modules/Button/style.js
  src/pages/History/index.jsx
  src/pages/LabRental/LabAuthManage/index.jsx
  src/pages/LabRental/LabAuthManage/style.js
  src/pages/LabRental/LabInformation/index.jsx
  src/pages/LabRental/LabRentalSched/index.jsx
  src/pages/LabRental/LabRentalSched/style.js
  src/pages/LabRental/index.jsx
  src/pages/LabRental/style.js
  src/pages/Login/index.jsx
  src/pages/NotFound/index.jsx
  src/pages/NotFound/style.js
  src/router/Router.js
Labels: 🪡 Design, 📁 Feat

#70 예외 처리 및 기능 추가
  src/api/api.js
  src/components/AddCartEquip/index.jsx
  src/components/AddCartEquip/style.js
  src/components/DatePicker/DualDatePicker/index.jsx
  src/components/DatePicker/DualDatePicker/style.js
  src/components/DatePicker/SingularDatePicker/index.jsx
  src/components/DatePicker/SingularDatePicker/style.js
  src/components/DatePicker/index.jsx
  src/components/DetailDesc/DetailDescInput/index.jsx
  src/components/DetailDesc/index.jsx
  src/components/EquipSched/ReturnModal/index.jsx
  src/components/EquipSched/index.jsx
  src/components/ItemListWrap/index.jsx
  src/components/ItemReserveHist/ItemResHistTbl/index.jsx
  src/components/ItemReserveHist/ItemResHistTbl/style.js
  src/components/ItemReserveHist/index.jsx
  src/components/ItemReserveHist/style.js
  src/components/SchedList/index.jsx
  src/components/UserHist/index.jsx
  src/components/UserHist/style.js
  src/pages/AddEquipment/index.jsx
  src/pages/EquipmentDetail/index.jsx
  src/pages/EquipmentList/index.jsx
  src/pages/EquipmentList/style.js
  src/pages/History/EquipRentalHistory/index.jsx
  src/pages/History/style.js
  src/pages/RentalStatus/index.jsx
  src/pages/RentalStatus/style.js
  src/store/index.js
  src/store/reducer/authReceiveSlice.js
  src/store/reducer/datePickerSlice.js
  src/store/reducer/modifyEquipSlice.js
Labels: 🚨 Bug, 📁 Feat, 🔧 Fix, 🧩 Refactor

#71 Feat: 기자재 대여 이력 api 구현
  src/api/api.js
  src/components/UserHist/index.jsx
  src/components/UserHist/style.js
  src/components/UserState/index.jsx
  src/data/rentalStatus.js
  src/pages/History/style.js
  src/pages/LabRental/LabRentalSched/index.jsx
Labels: 📁 Feat

#73 Chore : yml run 명령어 수정
  .github/workflows/main.yml
Labels: 🔧 Fix

#74 Chore : npm 의존성 충돌 관련 오류 수정
  .github/workflows/main.yml
Labels: 🔧 Fix

#78 남은 기자재 개수 조회 기능
  .eslintrc
  .prettierrc
  src/api/api.js
  src/components/AddCartEquip/index.jsx
  src/components/DatePicker/DualDatePicker/index.jsx
  src/components/EquipListWrap/GalType/index.jsx
  src/components/EquipListWrap/GalType/style.js
  src/components/EquipListWrap/ListType/index.jsx
  src/components/EquipListWrap/ListType/style.js
  src/components/EquipListWrap/index.jsx
  src/components/EquipListWrap/style.js
  src/components/EquipSched/style.js
  src/components/Header/index.jsx
  src/components/ItemListWrap/index.jsx
  src/components/NavBar/index.jsx
  src/components/UserHist/index.jsx
  src/components/WeekPicker/index.jsx
  src/context/Context.js
  src/layouts/AuthWrapper/index.jsx
  src/pages/AddEquipment/index.jsx
  src/pages/AuthSuccess/index.jsx
  src/pages/EquipmentCart/EquipmentBox/index.jsx
  src/pages/EquipmentCart/RentalApplication/index.jsx
  src/pages/EquipmentCart/RentalSuccess/index.jsx
  src/pages/EquipmentDetail/index.jsx
  src/pages/EquipmentItemDetail/index.jsx
  src/pages/EquipmentList/index.jsx
  src/pages/EquipmentRental/index.jsx
  src/pages/ForgotPassword/index.jsx
  src/pages/Login/index.jsx
  src/pages/NotFound/index.jsx
  src/pages/SignUp/index.jsx
  src/router/Router.js
Labels: 📁 Feat, 🔧 Fix

#79 Feat: 관리자 랩실 대여 관리 마크업
  src/components/LabSched/CancelModal/index.jsx
  src/components/LabSched/CancelModal/style.js
  src/components/LabSched/LabSchedList/index.jsx
  src/components/LabSched/LabSchedList/style.js
  src/components/LabSched/index.jsx
  src/components/LabSched/style.js
  src/pages/LabRental/LabAuthManage/index.jsx
  src/pages/LabRental/LabAuthManage/style.js
  src/pages/LabRental/index.jsx
  src/pages/LabRental/style.js
Labels: 📁 Feat

#80 예외 처리 및 기능 추가
  src/api/api.js
  src/components/AddCartEquip/index.jsx
  src/components/AddCartEquip/style.js
  src/components/DatePicker/SingularDatePicker/index.jsx
  src/components/DatePicker/index.jsx
  src/components/DetailDesc/DetailDescInput/index.jsx
  src/components/DetailDesc/style.js
  src/components/EquipCartList/ListItem/index.jsx
  src/components/EquipCartList/ModifyModal/ModifyComp/index.jsx
  src/components/EquipCartList/ModifyModal/index.jsx
  src/components/EquipCartList/ModifyModal/style.js
  src/components/EquipCartList/index.jsx
  src/components/EquipListWrap/ListType/index.jsx
  src/components/ProfileMenu/index.jsx
  src/components/WeekPicker/index.jsx
  src/pages/AddEquipment/index.jsx
  src/pages/EquipmentCart/EquipmentBox/index.jsx
  src/pages/EquipmentDetail/index.jsx
  src/pages/EquipmentDetail/style.js
  src/pages/EquipmentList/index.jsx
  src/store/index.js
  src/store/reducer/cartListSlice.js
  src/store/reducer/datePickerSlice.js
Labels: 📁 Feat, 🧩 Refactor

#81 관리자 - 대여 현황 페이지 수정 및 랩실 관리 페이지 구현
  src/api/api.js
  src/components/DatePicker/SingularDatePicker/index.jsx
  src/components/DatePicker/index.jsx
  src/components/EquipSched/CancelModal/index.jsx
  src/components/LabCalendar/index.jsx
  src/components/LabCalendar/style.js
  src/components/LabPenalty/index.jsx
  src/components/LabPenalty/style.js
  src/components/LabReserveWrap/index.jsx
  src/components/SchedList/SchedListComp/index.jsx
  src/components/SchedList/index.jsx
  src/context/Context.js
  src/pages/LabRental/LabRentalSched/index.jsx
  src/pages/LabRental/LabRentalSched/style.js
  src/pages/LabRental/index.jsx
  src/pages/RentalStatus/index.jsx
  src/store/index.js
  src/store/reducer/LabControllerSlice.js
  src/store/reducer/authReceiveSlice.js
Labels: 📁 Feat, 🔧 Fix

#84 디자인 수정사항 적용
  src/components/LabReserveWrap/style.js
  src/context/Context.js
  src/pages/AddEquipment/index.jsx
  src/pages/AddEquipment/style.js
  src/pages/EquipmentDetail/style.js
Labels: 🪡 Design

#83 관리자 히스토리, 페이지네이션 구현 및 theme color 적용
  src/api/api.js
  src/components/AddCartEquip/style.js
  src/components/Application/LabConfirmTable/style.js
  src/components/DatePicker/DualDatePicker/index.jsx
  src/components/DatePicker/style.js
  src/components/EquipStatistics/index.jsx
  src/components/EquipStatistics/style.js
  src/components/ItemCalendar/style.js
  src/components/LabCalendar/style.js
  src/components/LabSched/style.js
  src/components/Modal/style.js
  src/components/PenaltyState/style.js
  src/components/UserHist/style.js
  src/components/WeekPicker/style.js
  src/pages/History/EquipRentalHistory/index.jsx
  src/pages/History/style.js
  src/store/reducer/datePickerSlice.js
Labels: 📁 Feat, ✨ Style

#85 Feat: 히스토리, 내대여정보 마크업 완성
  src/components/DatePicker/DualDatePicker/index.jsx
  src/components/DatePicker/DualDatePicker/style.js
  src/components/EquipStatistics/index.jsx
  src/components/ExcelDownload/index.jsx
  src/components/ExcelDownload/style.js
  src/components/ItemListWrap/ItemListComp/index.jsx
  src/components/LabCalendar/style.js
  src/components/LabHist/index.jsx
  src/components/LabHist/style.js
  src/components/LabPenalty/style.js
  src/components/LabSched/style.js
  src/components/LabStatistics/index.jsx
  src/components/LabStatistics/style.js
  src/components/Modal/style.js
  src/components/Pagination/index.jsx
  src/components/Pagination/style.js
  src/components/UserHist/UserEquipHist/index.jsx
  src/components/UserHist/UserLabHist/index.jsx
  src/components/UserHist/UserPenaltyHist/index.jsx
  src/components/UserHist/index.jsx
  src/components/UserState/UserEquipState/index.jsx
  src/components/UserState/UserLabState/index.jsx
  src/components/UserState/UserPenaltyState/index.jsx
  src/components/UserState/index.jsx
  src/components/UserState/style.js
  src/data/rentalStatus.js
  src/pages/EquipmentCart/RentalApplication/index.jsx
  src/pages/EquipmentList/index.jsx
  src/pages/History/EquipRentalHistory/index.jsx
  src/pages/History/LabRentalHistory/index.jsx
  src/pages/History/index.jsx
  src/pages/History/style.js
Labels: 🪡 Design, 📁 Feat, 🧩 Refactor, ✨ Style

#86 오류 수정
  src/components/EquipCartList/ModifyModal/ModifyComp/index.jsx
  src/pages/EquipmentList/index.jsx
Labels: 🔧 Fix

#87 Feat: Quill Editor 추가
  package.json
  src/components/QuillUI/QuillEditor/index.jsx
  src/components/QuillUI/QuillViewer/index.jsx
  src/components/QuillUI/index.jsx
  src/components/QuillUI/style.js
  src/components/ToastUI/ToastEditor/index.jsx
  src/components/ToastUI/ToastViewer/index.jsx
  src/components/ToastUI/index.jsx
  src/components/ToastUI/style.js
  src/pages/LabRental/LabInformation/index.jsx
Labels: 🪡 Design, 📁 Feat, 🔧 Fix, 💣 Remove, ✨ Style

#88 Fix: color 지정하면 안 보이는 버그 수정
  src/components/QuillUI/style.js
Labels: 🔧 Fix

#89 랩실 관련 기능 연결
  package-lock.json
  src/api/api.js
  src/assets/adminLogo.svg
  src/assets/adminLogo.webp
  src/assets/logo.svg
  src/assets/logo.webp
  src/components/Application/ApplicationForm/index.jsx
  src/components/Application/LabConfirmTable/index.jsx
  src/components/Header/index.jsx
  src/components/Header/style.js
  src/components/LabCalendar/index.jsx
  src/components/LabReserveWrap/index.jsx
  src/components/LabSched/LabSchedList/index.jsx
  src/components/LabSched/LabSchedList/style.js
  src/components/LabSched/index.jsx
  src/components/LabSched/style.js
  src/layouts/AuthWrapper/index.jsx
  src/layouts/AuthWrapper/style.js
  src/layouts/MainWrapper/index.jsx
  src/pages/LabRental/LabAuthManage/index.jsx
  src/pages/LabRental/LabRentalApplication/index.jsx
Labels: 📁 Feat

#91 랩실 관련 기능 수정 및 구현
  public/index.html
  src/api/api.js
  src/components/LabCalendar/index.jsx
  src/components/LabPenalty/index.jsx
  src/components/LabPenalty/style.js
  src/components/LabReserveWrap/index.jsx
  src/components/QuillUI/index.jsx
  src/font/Pretendard-Bold.subset.woff
  src/font/Pretendard-Bold.subset.woff2
  src/font/Pretendard-Medium.subset.woff
  src/font/Pretendard-Medium.subset.woff2
  src/font/Pretendard-Regular.subset.woff
  src/font/Pretendard-Regular.subset.woff2
  src/font/Pretendard-SemiBold.subset.woff
  src/font/Pretendard-SemiBold.subset.woff2
  src/hook/useInput.js
  src/hook/usePreventRefresh.js
  src/hook/useTitle.js
  src/pages/AddEquipment/index.jsx
  src/pages/EquipmentCart/EquipmentBox/index.jsx
  src/pages/EquipmentCart/RentalApplication/index.jsx
  src/pages/EquipmentCart/RentalSuccess/index.jsx
  src/pages/EquipmentDetail/index.jsx
  src/pages/EquipmentItemDetail/index.jsx
  src/pages/EquipmentList/index.jsx
  src/pages/ForgotPassword/index.jsx
  src/pages/History/EquipRentalHistory/index.jsx
  src/pages/History/LabRentalHistory/index.jsx
  src/pages/History/PenaltyHistory/index.jsx
  src/pages/LabRental/LabAuthManage/index.jsx
  src/pages/LabRental/LabRentalApplication/index.jsx
  src/pages/LabRental/LabRentalSched/index.jsx
  src/pages/Login/index.jsx
  src/pages/RentalStatus/index.jsx
  src/pages/SetAccount/index.jsx
  src/pages/SignUp/index.jsx
  src/styles/globalStyle.js
Labels: 📁 Feat, 🔧 Fix

#92 추가 기능 구현
  src/components/AccountSettingComp/ChangeAccount/index.jsx
  src/components/AccountSettingComp/CheckPw/index.jsx
  src/components/SchedList/index.jsx
  src/components/UserState/UserEquipState/StateListComp/index.jsx
  src/components/UserState/UserEquipState/index.jsx
  src/pages/Login/index.jsx
  src/pages/SignUp/index.jsx
Labels: 📁 Feat

#93 디자인 수정 요청사항 적용
  src/components/Application/ToS/ToSText/index.jsx
  src/components/Application/ToS/index.jsx
  src/components/Application/ToS/style.js
  src/components/Application/index.jsx
  src/components/Application/style.js
  src/components/EquipStatistics/style.js
  src/components/Header/style.js
  src/components/LabCalendar/index.jsx
  src/components/LabCalendar/style.js
  src/components/LabStatistics/style.js
  src/components/PenaltyState/index.jsx
  src/components/PenaltyState/style.js
  src/components/ProfileMenu/style.js
  src/components/UserState/UserLabState/index.jsx
  src/modules/TabNav/style.js
  src/pages/EquipmentList/index.jsx
  src/pages/EquipmentList/style.js
  src/pages/History/PenaltyHistory/index.jsx
  src/pages/History/style.js
Labels: 🪡 Design, 📁 Feat

#94 대여관리 페이지 한울관 고정 출력 및 반납일 초과 디자인 수정
  src/components/SchedList/index.jsx
  src/components/SchedList/style.js
  src/store/reducer/authReceiveSlice.js
Labels: 🪡 Design, 📁 Feat

#95 랩실 캘린더 및 title 오류 수정
  src/components/Application/ApplicationForm/index.jsx
  src/components/Application/index.jsx
  src/components/LabCalendar/index.jsx
  src/hook/useTitle.js
  src/pages/EquipmentDetail/index.jsx
  src/pages/EquipmentItemDetail/index.jsx
  src/pages/LabRental/LabRentalApplication/index.jsx
Labels: 🔧 Fix

#96 Feat: EmptyData 컴포넌트 추가 및 적용
  src/components/EmptyData/index.jsx
  src/components/EmptyData/style.js
  src/components/EquipSched/index.jsx
  src/components/EquipSched/style.js
  src/components/LabHist/index.jsx
  src/components/LabHist/style.js
  src/components/LabSched/index.jsx
  src/components/LabSched/style.js
  src/components/LabStatistics/index.jsx
  src/components/LabStatistics/style.js
  src/components/PenaltyState/index.jsx
  src/components/UserHist/UserEquipHist/index.jsx
  src/components/UserHist/UserLabHist/index.jsx
  src/components/UserHist/UserPenaltyHist/index.jsx
  src/components/UserState/UserEquipState/index.jsx
  src/components/UserState/UserLabState/index.jsx
  src/components/UserState/style.js
  src/pages/EquipmentCart/EquipmentBox/index.jsx
  src/pages/History/LabRentalHistory/index.jsx
  src/pages/History/PenaltyHistory/index.jsx
Labels: 📁 Feat, 🧩 Refactor

#98 Feat: 사용자 내대여정보 랩실 api 구현
  src/api/api.js
  src/components/UserHist/UserEquipHist/index.jsx
  src/components/UserHist/UserLabHist/index.jsx
  src/components/UserState/UserLabState/index.jsx
Labels: 📁 Feat

#99 예외 처리 및 성능 최적화
  public/index.html
  src/components/ItemListWrap/ItemListComp/index.jsx
  src/components/ItemListWrap/index.jsx
  src/components/SchedList/index.jsx
  src/components/UserState/style.js
  src/data/category.js
  src/pages/AddEquipment/style.js
  src/pages/EquipmentDetail/index.jsx
  src/pages/EquipmentDetail/style.js
  src/pages/EquipmentItemDetail/style.js
  src/pages/EquipmentList/index.jsx
  src/router/Router.js
Labels: ✏️ Docs, 🧩 Refactor

#100 페널티 조회 구현 및 랩실 취소 및 에러 해결
  src/api/api.js
  src/components/AccountSettingComp/ChangeAccount/index.jsx
  src/components/AccountSettingComp/CheckPw/index.jsx
  src/components/Header/HeaderUserInfo/index.jsx
  src/components/ProfileMenu/index.jsx
  src/components/ProfileMenu/style.js
  src/components/UserHist/UserPenaltyHist/index.jsx
  src/components/UserState/UserLabState/StateListComp/index.jsx
  src/components/UserState/UserLabState/index.jsx
  src/modules/Input/index.jsx
  src/pages/ForgotPassword/index.jsx
  src/pages/SignUp/index.jsx
Labels: 📁 Feat, 🔧 Fix, 🧩 Refactor

#101 Fix : dayjs updateLocale 오류 해결
  src/components/DatePicker/index.jsx
Labels: 🔧 Fix
