Repository KW-GIRIGIRI/kw-rental, pull requests merged in 2023-10, with the labels that each got.

#127 랩실 운영 요일 변경 기능 및 전체 온오프 기능 구현
  src/api/api.js
  src/components/Application/LabConfirmTable/index.jsx
  src/components/DatePicker/DualDatePicker/index.jsx
  src/components/DatePicker/SingularDatePicker/index.jsx
  src/components/DatePicker/index.jsx
  src/components/DatePicker/style.js
  src/components/EquipCartList/ModifyModal/ModifyComp/index.jsx
  src/components/LabCalendar/index.jsx
  src/components/NavBar/index.jsx
  src/components/UserState/UserLabState/StateListComp/index.jsx
  src/components/WeekPicker/index.jsx
  src/components/WeekPicker/style.js
  src/data/weekDay.js
  src/hook/useModal.js
  src/layouts/MainWrapper/index.jsx
  src/pages/LabRental/LabRentalApplication/index.jsx
  src/pages/LabRental/LabRentalSched/index.jsx
  src/pages/Login/index.jsx
  src/pages/Login/style.js
  src/pages/ManageSchedule/index.jsx
  src/pages/ManageSchedule/style.js
  src/router/Router.js
  src/store/index.js
  src/store/reducer/operationDaySlice.js
Labels: 🪡 Design, 📁 Feat, 🔧 Fix, 🧩 Refactor

#128 chore: 안 쓰는 라이브러리 삭제
  package-lock.json
  package.json
Labels: 🗝️ Chore

#130 Chore : 개발 의존성 패키지 분리
  package-lock.json
  package.json
Labels: 🗝️ Chore

#131 DatePicker 로직 변경 및 적용
  .prettierrc
  src/components/AddCartEquip/index.jsx
  src/components/DatePicker/DualDatePicker/index.jsx
  src/components/DatePicker/SingularDatePicker/index.jsx
  src/components/DatePicker/index.jsx
  src/components/UserHist/index.jsx
  src/pages/History/EquipRentalHistory/index.jsx
  src/pages/History/LabRentalHistory/index.jsx
Labels: 📁 Feat, 🔧 Fix
