Repository KW-GIRIGIRI/kw-rental, pull requests merged in 2023-06, with the labels that each got.

#103 Fix: 모달 한 번 끄면 다시 안 뜨는 버그 수정
  src/components/LabSched/CancelModal/index.jsx
Labels: 🔧 Fix

#104 페널티 기능 구현
  public/favicon.ico
  public/index.html
  src/api/api.js
  src/components/DatePicker/index.jsx
  src/components/LabCalendar/index.jsx
  src/components/LabPenalty/index.jsx
  src/components/LabReserveWrap/index.jsx
  src/components/Pagination/index.jsx
  src/components/Pagination/style.js
  src/components/PenaltyState/StateListComp/index.jsx
  src/components/PenaltyState/index.jsx
  src/components/UserHist/UserPenaltyHist/index.jsx
  src/components/UserState/UserPenaltyState/index.jsx
  src/components/UserState/style.js
  src/data/penaltyStatus.js
  src/pages/AddEquipment/index.jsx
  src/pages/History/PenaltyHistory/index.jsx
  src/store/reducer/authReceiveSlice.js
  src/styles/globalStyle.js
Labels: 📁 Feat, 🔧 Fix

#105 코드 리팩토링 및 오류 수정
  src/api/api.js
  src/components/LabCalendar/index.jsx
Labels: 🔧 Fix, 🧩 Refactor

#106 Design: 뒤로 가기 버튼 삭제
  src/components/LabPenalty/index.jsx
  src/pages/LabRental/LabRentalSched/index.jsx
  src/pages/LabRental/LabRentalSched/style.js
Labels: 🪡 Design

#107 예외 처리
  src/components/DatePicker/DualDatePicker/index.jsx
  src/components/DatePicker/SingularDatePicker/index.jsx
  src/components/EquipListWrap/GalType/index.jsx
  src/components/LabCalendar/index.jsx
  src/components/LabPenalty/index.jsx
  src/pages/RentalStatus/index.jsx
  src/router/Router.js
Labels: 🔧 Fix

#108 Design: section padding, 내대여정보 색 수정
  src/components/UserHist/style.js
  src/components/UserState/style.js
  src/pages/History/style.js
  src/pages/LabRental/style.js
  src/pages/RentalStatus/style.js
Labels: 🪡 Design

#109 예외 처리 및 최적화
  src/api/api.js
  src/assets/icon-menu.svg
  src/assets/icon-profile-menu.svg
  src/components/DatePicker/SingularDatePicker/index.jsx
  src/components/LabCalendar/index.jsx
  src/components/LabPenalty/index.jsx
  src/components/LabReserveWrap/index.jsx
  src/components/LabSched/LabSchedList/style.js
  src/components/ProfileMenu/index.jsx
  src/components/SchedList/SchedListComp/index.jsx
  src/components/UserState/UserEquipState/StateListComp/index.jsx
  src/pages/EquipmentList/index.jsx
  src/pages/LabRental/LabRentalSched/index.jsx
Labels: 📁 Feat, 🔧 Fix

#110 Feat : 소모품 관련 코드 삭제 및 스타일 수정
  src/components/DetailDesc/DetailDescInput/index.jsx
  src/components/SchedList/SchedListComp/index.jsx
  src/components/SchedList/SchedListComp/style.js
  src/pages/AddEquipment/index.jsx
  src/pages/EquipmentDetail/style.js
Labels: 📁 Feat

#111 예외처리
  public/index.html
  src/components/AddCartEquip/index.jsx
  src/components/DatePicker/DualDatePicker/index.jsx
  src/components/DatePicker/SingularDatePicker/index.jsx
  src/components/DatePicker/index.jsx
  src/hook/useTitle.js
  src/pages/EquipmentDetail/index.jsx
  src/pages/EquipmentItemDetail/index.jsx
  src/pages/Login/index.jsx
Labels: 🔧 Fix

#112 Lab api f2
  src/api/api.js
  src/components/LabStatistics/index.jsx
  src/components/QuillUI/QuillEditor/index.jsx
  src/components/QuillUI/index.jsx
  src/pages/History/LabRentalHistory/index.jsx
Labels: 📁 Feat

#114 랩실 ONOFF 조회 및 기능 구현
  src/api/api.js
  src/components/LabCalendar/index.jsx
  src/components/LabReserveWrap/index.jsx
  src/components/LabReserveWrap/style.js
  src/components/QuillUI/index.jsx
  src/components/QuillUI/style.js
  src/pages/LabRental/LabRentalSched/index.jsx
  src/pages/LabRental/LabRentalSched/style.js
Labels: 📁 Feat, 🧩 Refactor

#115 Fix : 랩실 페널티 이력 요청 값 수정
  src/api/api.js
  src/components/LabPenalty/index.jsx
  src/components/LabReserveWrap/index.jsx
Labels: 🔧 Fix

#116 Design: 랩실 소개 img max-width 설정
  src/components/QuillUI/QuillEditor/index.jsx
  src/components/QuillUI/style.js
Labels: 🪡 Design

#117 대여 목적 확인 및 회원 관련 기능 구현
  src/api/api.js
  src/assets/icon-msg.svg
  src/components/AccountSettingComp/ChangeAccount/index.jsx
  src/components/AccountSettingComp/CheckPw/index.jsx
  src/components/DatePicker/index.jsx
  src/components/LabSched/LabSchedList/index.jsx
  src/components/LabSched/LabSchedList/style.js
  src/components/LabSched/style.js
  src/components/PurposeModal/index.jsx
  src/components/PurposeModal/style.js
  src/components/SchedList/index.jsx
  src/components/SchedList/style.js
  src/pages/Login/index.jsx
  src/pages/SetAccount/index.jsx
  src/styles/globalStyle.js
Labels: 📁 Feat

#118 예외처리 및 기능구현
  package-lock.json
  package.json
  src/api/api.js
  src/components/Application/ApplicationForm/index.jsx
  src/components/LabCalendar/index.jsx
  src/components/LabPenalty/index.jsx
  src/components/LabReserveWrap/index.jsx
  src/components/LabSched/LabSchedList/style.js
  src/index.js
  src/pages/EquipmentDetail/index.jsx
  src/pages/ForgotPassword/index.jsx
  src/pages/LabRental/LabRentalApplication/index.jsx
  src/pages/LabRental/LabRentalSched/index.jsx
  src/store/index.js
  src/store/reducer/LabControllerSlice.js
  src/styles/globalStyle.js
Labels: 📁 Feat, 🔧 Fix

#120 기능 구현 및 오류 해결
  src/api/api.js
  src/components/ItemListWrap/ItemListComp/index.jsx
  src/components/ItemReserveHist/ItemResHistTbl/index.jsx
  src/components/ItemReserveHist/ItemResHistTbl/style.js
  src/components/ItemReserveHist/index.jsx
  src/components/SchedList/index.jsx
  src/pages/AddEquipment/index.jsx
  src/pages/EquipmentItemDetail/index.jsx
Labels: 📁 Feat, 🔧 Fix

#119 Fix: 랩실 통계 페이지네이션 0으로 보이는 UI 수정
  src/pages/History/LabRentalHistory/index.jsx
Labels: 🔧 Fix

#121 예외처리
  src/api/api.js
  src/components/EquipStatistics/index.jsx
  src/components/ExcelDownload/index.jsx
  src/components/ExcelDownload/style.js
  src/pages/EquipmentList/index.jsx
  src/pages/History/EquipRentalHistory/index.jsx
  src/pages/History/style.js
  src/pages/SignUp/index.jsx
Labels: 📁 Feat

#122 Exception handling
  src/App.js
  src/components/AccountSettingComp/ChangeAccount/index.jsx
  src/components/Application/ApplicationForm/index.jsx
  src/components/DatePicker/DualDatePicker/index.jsx
  src/components/DatePicker/SingularDatePicker/index.jsx
  src/components/DatePicker/index.jsx
  src/components/ExcelDownload/index.jsx
  src/components/ItemListWrap/index.jsx
  src/components/LabCalendar/index.jsx
  src/components/LabReserveWrap/index.jsx
  src/components/UserHist/UserPenaltyHist/index.jsx
  src/components/WeekPicker/index.jsx
  src/pages/AddEquipment/index.jsx
  src/pages/EquipmentDetail/index.jsx
  src/pages/EquipmentList/index.jsx
  src/pages/LabRental/LabRentalSched/index.jsx
  src/pages/LabRental/index.jsx
Labels: 📁 Feat, 🔧 Fix, 🧩 Refactor, 🗝️ Chore

#123 예외 처리
  src/api/api.js
  src/components/AddCartEquip/index.jsx
  src/components/Application/ApplicationForm/index.jsx
  src/components/DatePicker/DualDatePicker/index.jsx
  src/components/DatePicker/SingularDatePicker/index.jsx
  src/components/DetailDesc/DetailDescInput/index.jsx
  src/components/EquipCartList/ModifyModal/ModifyComp/index.jsx
  src/components/LabReserveWrap/index.jsx
  src/components/LabReserveWrap/style.js
  src/components/UserHist/index.jsx
  src/components/UserState/UserPenaltyState/index.jsx
  src/pages/EquipmentCart/RentalApplication/index.jsx
  src/pages/EquipmentDetail/index.jsx
  src/pages/EquipmentItemDetail/index.jsx
  src/pages/History/EquipRentalHistory/index.jsx
  src/pages/History/LabRentalHistory/index.jsx
Labels: 🪡 Design, 📁 Feat, 🔧 Fix, 🧩 Refactor

#124 랩실 소개 페이지 UI, 오류 수정 및 기능 구현
  src/components/QuillUI/QuillEditor/index.jsx
  src/components/QuillUI/index.jsx
  src/components/QuillUI/style.js
  src/store/reducer/LabControllerSlice.js
Labels: 🪡 Design, 📁 Feat, 🔧 Fix

#126 Fix : 관리자 비밀번호 설정 오류 수정
  src/api/api.js
Labels: 🔧 Fix
