Repository KW-GIRIGIRI/kw-rental, pull requests merged in 2023-11, with the labels that each got.

#132 피드백 반영 및 기능 수정
  src/components/AddCartEquip/index.jsx
  src/components/DatePicker/DualDatePicker/index.jsx
  src/components/DatePicker/DualDatePicker/style.js
  src/components/DatePicker/index.jsx
  src/components/DetailDesc/DetailDescInput/index.jsx
  src/components/DetailDesc/index.jsx
  src/components/DetailDesc/style.js
  src/components/EquipCartList/ModifyModal/ModifyComp/index.jsx
  src/components/EquipCartList/ModifyModal/style.js
  src/components/LabCalendar/index.jsx
  src/components/UserHist/UserLabHist/index.jsx
  src/components/UserState/UserLabState/index.jsx
  src/components/WeekPicker/index.jsx
  src/pages/AddEquipment/index.jsx
  src/pages/EquipmentDetail/style.js
  src/pages/LabRental/LabRentalApplication/index.jsx
Labels: 🪡 Design, 📁 Feat, 🔧 Fix

#133 Refactor : 기자재 수정 페이지 API 변경사항 반영하여 request 값 수정
  src/api/api.js
  src/pages/AddEquipment/index.jsx
Labels: 🧩 Refactor

#134 구글 애널리틱스 4 연동
  package-lock.json
  package.json
  src/App.js
Labels: 📁 Feat, 🗝️ Chore

#136 안내사항 및 대여목적 스타일 변경
  src/components/Application/ApplicationForm/index.jsx
  src/pages/EquipmentDetail/style.js
Labels: 🪡 Design

#137 수정 페이지 router 및 숫자 타입 input 수정
  src/components/DetailDesc/DetailDescInput/index.jsx
  src/pages/AddEquipment/index.jsx
  src/pages/ForgotPassword/index.jsx
  src/pages/SignUp/index.jsx
Labels: 🔧 Fix
